name: aoc
source-dirs: src
dependencies:
- base >= 4.7 && < 5
- containers
- extra
- lens
- parsec
executables:
  day01: { main: Day01, other-modules: [] }
  day02: { main: Day02, other-modules: [] }
  day03: { main: Day03, other-modules: [] }
  day04: { main: Day04, other-modules: [] }
  day05: { main: Day05, other-modules: [] }
  day06: { main: Day06, other-modules: [] }
  day07: { main: Day07, other-modules: [] }
  day08: { main: Day08, other-modules: [] }
  day09: { main: Day09, other-modules: [] }
  day10: { main: Day10, other-modules: [] }
  day11: { main: Day11, other-modules: [] }
  day12: { main: Day12, other-modules: [] }
  day13: { main: Day13, other-modules: [] }
  day14: { main: Day14, other-modules: [] }
