[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"

[features]
day1 = []
day2 = []
day3 = []
day4 = []
day5 = []
day6 = []
day7 = []
day8 = []
day9 = []
default = ["day1", "day2", "day3", "day4", "day5", "day6", "day7", "day8", "day9"]
